name: Telegram Notification

on:
  push:
    branches:
      - master
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Commit Info
        id: extract
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_HASH=$(git log -1 --pretty=format:"%h")
          echo "msg=$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Send Notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: "-1003965036298"
          token: "8976405279:AAEg1lt_btbscr8BlDG2pJ0bL-2fX6PuDmk"
          message: |
            🚀 *New Update on Apahayo (WaEnhancer)* 🚀

            👤 *Author*: ${{ steps.extract.outputs.author }}
            📝 *Commit*: ${{ steps.extract.outputs.msg }}
            🔗 *Hash*: `${{ steps.extract.outputs.hash }}`

            View changes: https://github.com/${{ github.repository }}/commit/${{ steps.extract.outputs.hash }}
          format: markdown
